package com.IdeaBox.models.usuarios;

public enum Cargo {
	ADMINISTRADOR,	ADMINISTRADOR_SISTEMAS, ADMINISTRADOR_BANCO_DE_DADOS, 	ADMINISTRADOR_REDE, ANALISTA, 
	ANALISTA_BI,ANALISTA_TI, ANALISTA_SEGURANÇA_DA_INFORMAÇÃO, ANALISTA_SISTEMAS, ANALISTA_WEB, ANALISTA_TELECOMUNICAÇÕES,
	ANALISTA_SUPORTE, ANALISTA_BANCO_DE_DADOS, ANALISTA_DE_DESENVOLVIMENTO_DE_SISTEMAS, ANALISTA_RH, ANALISTA_CONSULTOR,
	ANALISTA_DE_NEGOCIOS, ANALISTA_PROCESSOS, ANALISTA_PRODUÇÃO, ANALISTA_SISTEMAS_AUTOMAÇÃO,	ANALISTA_SUPORTE_MAINFRAME,
	ANALISTA_ADMINISTRATIVO, ANALISTA_FINANCEIRO, APONTADOR, ARQUITETO_REDE_DE_INFORMÁTICA, ASSISTENTE_DE_QUALIDADE,
	ASSISTENTE_TI, ASSISTENTE_ADMINISTRATIVIO, ASSISTENTE_COBRANÇA,ASSISTENTE_CONTAS_A_PAGAR, ASSISTENTE_CONTAS_A_RECEBER,
	ASSISTENTE_FISCAL, ASSISTENTE_CONTABIL, ASSISTENTE_FINANCEIRO, ASSISTENTE_DE_RH, ASSISTENTE_DE_VENDAS, ATENDENTE_HELP_DESK,
	ATENDENTE, AUXIXILIAR, AUXILIAR_DE_LIMPEZA, AUXILIAR_DE_SERVIÇOS_GERAIS, AUXILIAR_FINANCEIRO, AUXILIAR_RH, AUXILIAR_DE_VENDAS,
	BUSINESS_INTELLIGENCE, CHIEF_TECNOLOGY_OFFICER, CHIEF_DATA_OFFICER, CIENTISTA_DE_DADOS, CONSULTOR, CONSULTOR_TI, COORDENADOR_TI,
	COORDENADOR_WEB, COORDENADOR, COORDENADOR_RH, COPEIRA, 	DESENVOLVEDOR, DESENVOLVEDOR_FULL_STACK, DESENVOLVEDOR_MOBILE, 
	DESENVOLVEDOR_PROJETOS_ERP, DESENVOLVEDOR_WEB, DESENHISTA_GRAFICO, DESENHISTA_EDITORIAL, DESIGNER, DESIGNER_GRAFICO,
	DESINER_DE_GAMES, DIRETOR, DOCUMENTADOR, ENGENHEIRO, ENGENHEIRO_DE_IA, ENGENHEIRO_DE_SOFTWARE, ENGENHEIRO_DE_DADOS,
	ENGENHEIRO_DE_REDE, ENGENHEIRO_DE_SUPORTE, ESPECIALISTA, ESPECIALISTA_CLOUD_COMPUTING, ESTAGIARIO, FINANCEIRO,
	GERENTE, GERENTE_FINANCEIRO, GERENTE_TI, GERENTE_PROJETOS, GERENTE_SEGURANÇA_DA_INFORMAÇÃO, GERENTE_PRODUTOS_SOFTWARE,
	GERENTE_DE_NEGOCIOS, GERENTE_DE_SISTEMAS, GERENTE_DE_SUPORTE, GERENTE_TELEPROCESSAMENTO, GERENTE_DE_INFRAESTRUTURA,
	OPERADOR_DE_PROCESSAMENTO_DE_DADOS, OPERADOR_DE_SISTEMA_DE_COMPUTADOR, OPERADOR_DE_SISTEMAS_COMPUTACIONAIS_DE_REDE,
	PESQUISADOR_CIÊNCIAS_COMPUTAÇÃO_E_TI, PORTEIRO,	PROGRAMADOR, PROGRAMADOR_JOGOS_DIGITAIS, PROGRAMADOR_JAVA,PROGRAMADOR_FRONT_END, 
	PROGRAMADOR_PYTHON, PROGRAMADOR_WEB, PROGRAMADOR_DE_COMPUTADOR, PROGRAMADOR_TI, PROGRAMADOR_CD_ROM, 
    PROGRAMADOR_APLICATRIVOS_EDUCACIONAIS_E_ENTRETENIMENTO,	PROGRAMADOR_MULTIMIDIA,	PROFISSIONAL_DEVOPS, RH, RECEPCIONISTA,
    SECRETARIA, SEGURANÇA, SUPERVISOR,SUPERVISOR_TI, SUPORTE, TRAINEE_TI, TRAINEE, TECNICO, TECNICO_MANUTENÇÃO_DE_EQUIPAMENTOS,	
    TECNICO_HELPDESK, TECNICO_APLICAÇÃO,TELEMARKETING, TELEFONISTA, TECNOLOGO_GESTÃO_TI, TECNOLOGO_BANCO_DE_DADOS, UX_UI, VENDEDOR,
 	VIGILANTE, WEBMASTER
}
